---
title: "研究室の特色と進学希望者へ"
---
## 学部の教育目標

学部では，以下の教育目標をもってゼミを行っています。

1. 臨床心理学や計算論的臨床心理学・計算論的精神医学の考え方や研究方法を理解し，卒業論文としてまとめることができる。
1. 認知行動療法の基礎を理解し，今後の生活の中でのセルフヘルプの１つとして使える。
1. オープンサイエンスや実証に基づく医療・臨床心理実践の方法論を学び，今後の生活で科学・医療関連情報を有効に活用できる。

## 大学院(修士)の教育目標

大学院(修士)では，以下の教育目標をもってゼミを行っています。

1. 臨床心理学や計算論的臨床心理学・計算論的精神医学の考え方や研究方法を理解し，修士論文としてをまとめることができる。
1. 認知行動療法の基礎と臨床応用を理解し，今後の臨床実践に用いることができる。
1. 実証に基づく医療・臨床心理実践の方法論を学び，今後の臨床実践や研究に用いることができる。

## 大学院(博士)の教育目標

大学院(博士)では，以下の教育目標をもってゼミを行っています。

1. 臨床心理学や計算論的臨床心理学・計算論的精神医学の考え方や研究方法について深く理解し，博士論文としてをまとめることができる。
1. 関心領域に関して包括的な知識を獲得し、自ら取り組むべき研究テーマを設定することができる。
1. 再現可能性やオープンサイエンスの観点から適切な研究方法と計算論的アプローチを用いた研究方法に関する専門家として活動できる。
1. 研究知見の社会での活用を意識した研究活動に取り組むことができる。

## 進学を希望される方へ
 
計算論的臨床心理学研究室へ進学を考えておられる方は，一度，国里の研究室をご訪問下さい。特に，他大学から受験を考えている方の場合は，国里や研究室の様子などを知ることが難しいかと思いますので，是非ともご活用下さい。また、心理学専攻全体の大学院進学説明会も行われますので、そちらも活用下さい。

### 研究室訪問の流れ

1. 国里まで，研究室を訪問を希望する旨をご連絡ください（連絡には以下のメールフォームを活用ください）。
2. 相談の上で，研究室訪問の日程を決めます。
3. 決められた日程に，専修大学生田キャンパスの国里の研究室にお越し下さい（オンライン面談も可能です）。

- 研究室訪問をご希望の方には大学院入試出願より前にお越しいただいています（大学院入試出願期間終了から入試当日までの間は研究室訪問をお受けしておりません）。研究室訪問をご希望の方は、スケジュールに余裕をもってご連絡ください（あまりに直前の場合は日程調整ができない可能性もあります）。
- 専修大学以外の大学に在学中の方の場合は，連絡する前に指導を受けている先生にご相談することをお勧めします。
- 研究室訪問時には，大学院で学びたい臨床の内容，取り組みたい研究の内容をお聞きするので，事前に用意しておくと良いかと思います。緊張される方も多いので，聞いておきたいことをメモしてこられると安心かと思います。
- 研究室訪問は，入学の選考や入学後の研究室配属とは無関係ですが，ご自身が学びたい臨床や行いたい研究ができるのか確認する機会としてご活用ください。

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSeVb0_ti9flHyGcRQcLESQO7Tzl3eH5hbCqXyzcGh7RWLQexA/viewform?embedded=true" 
width="100%" 
height="1000" 
frameborder="0" 
marginheight="0" 
marginwidth="0">Loading…</iframe>