---
title: "主な研究テーマ"
---

### うつや不安の発症・維持メカニズム

計算論的アプローチ(強化学習・ベイズ推論モデル)を用いて、うつや不安の発症・維持メカニズムの研究に取り組んでいます。関連する日本語論文を以下にリストアアップしていますので、詳細はそちらをお読み下さい。

- 国里愛彦(2021)恐怖の再発と潜在原因モデルー計算論的精神医学入門ー　基礎心理学研究, 40(1), 50-53.[Link](https://www.jstage.jst.go.jp/article/psychono/40/1/40_40.11/_pdf/-char/ja)
- 国里愛彦・片平健太郎・沖村 宰・山下祐一 (2019).うつに対する計算論的アプローチ：強化学習モデルの観点から　心理学評論, 62(1), 88-103. [Link](https://www.jstage.jst.go.jp/article/sjpr/62/1/62_88/_article/-char/ja/)
- 国里愛彦 (2018) 臨床心理学と認知モデリング　心理学評論, 61(1), 55-66. [Link](https://www.jstage.jst.go.jp/article/sjpr/61/1/61_55/_article/-char/ja/)

### 心理療法の作用メカニズム

計算論的アプローチ(ベイズ推論モデル)や心理ネットワークモデルなどを用いて、心理療法の作用プロセスの動的な側面について研究に取り組んでいます。関連する日本語論文を以下にリストアアップしていますので、詳細はそちらをお読み下さい。

- 国里愛彦・片平健太郎・沖村 宰・山下祐一(2022). 認知行動療法に対する計算論的アプローチ　認知行動療法研究, 48(1),1-10.　[Link](https://www.jstage.jst.go.jp/article/jjbct/advpub/0/advpub_20-036/_article/-char/ja/)
- 国里愛彦・山本哲也(2021). マインドフルネス研究の未来を切り開く新たな方法論　心理学評論,64(4), 599-618.[Link](https://www.jstage.jst.go.jp/article/sjpr/64/4/64_599/_article/-char/ja/)


うつや不安の発症・維持メカニズムや心理療法の作用メカニズムでの個人差について考える中で、計算論的個性記述心理学(computational idiographic psychology)のようなテーマにも関心を持っています。

### オープンサイエンス実践

オープンサイエンスや再現可能性高い研究を遂行するためのツールの開発と研究におけるワークフローについて研究を行っています。関連する日本語論文を以下にリストアアップしていますので、詳細はそちらをお読み下さい。

- 国里愛彦(2022). データ，解析コード，マテリアルをどのようにオープンにすればよいのか？　学会企画チュートリアル・セミナー「『心理学の７つの大罪』から考える心理学研究法」 教育心理学年報, 61, 294-296.[Link](https://www.jstage.jst.go.jp/article/arepj/61/0/61_291/_article/-char/ja/)
- 国里愛彦・土屋政雄(2022). 認知行動療法における研究の再現可能性を高める　認知行動療法研究,  48(2), 113-122. [Link](https://www.jstage.jst.go.jp/article/jjbct/48/2/48_21-004/_article/-char/ja)


